Fix #29: Error while modifying mode line.
karthink/popper pull request #30
Opened 2022-03-07 05:41 UTC by seagle0128

2022-03-08 05:49 UTC, karthink requested changes
This still fails on a non-list mode-line-format. Could you replace this function with

```elisp
(defun popper--modified-mode-line ()
  "Return modified mode-line string."
  (if (and popper-mode-line (consp mode-line-format))
      (if (member popper-mode-line mode-line-format)
          mode-line-format
        (append (cl-subseq (default-value 'mode-line-format) 0 popper-mode-line-position)
                (list popper-mode-line
                      (nthcdr popper-mode-line-position
                              (default-value 'mode-line-format)))))
    mode-line-format))
```

2022-03-08 05:49 UTC, karthink commented
Thanks for catching this!

2022-03-08 06:00 UTC, seagle0128 commented
@karthink Thanks for your reply! I've changed according to your great suggestion.

2022-03-08 06:07 UTC, merged

2022-03-08 06:07 UTC, karthink commented
Cheers @seagle0128!

2022-03-09 03:52 UTC, seagle0128 commented
@karthink I'd like mention the side-effect of the solution above. `popper-mode-line` doesn't respect `nil`. According to the doc, the mode line should be OFF. Thoughts?

2022-03-09 04:53 UTC, karthink commented
@seagle0128 Thank you for finding that. Fixed in [f9fef81](https://github.com/karthink/popper/commit/f9fef8192a7813903e73abeb46be58df16916e4c). Popper is now large enough that I need to write some tests, I think.

2022-03-09 06:02 UTC, seagle0128 commented
Agree! The tests are helpful to avoid the regression issues. 
I have to say I love this great package. Thank you very much!